### PR TITLE
Retirement of VIP Plugins UI

### LINKED ISSUE #38: Better 'Community' plugin handling
Right now we've duct-taped the regular plugins list table into the VIP Plugins UI. This is not great because:
- Activate/deactivate still goes through `wp-admin/plugins.php`, so you end up on the wrong page
- Includes Bulk Actions
- UI does not support loading regular plugins via code - if a plugin has been loaded via code, the UI needs to display that message

We should make a custom list table for regular plugins in the same way we did for shared plugins, and use that here. Currently, we're using the core plugins table, crammed into our VIP plugins page.

That would include replicating some functionality from `wp-admin/plugins.php` for activation/deactivation, etc.

### LINKED ISSUE #43: Don't load UI enabled plugins from inside the Plugins UI class
Something called Plugins UI should _only_ handle Plugins UI :)

Really confusing that it handles loading the plugins also. Means it needs to be included from the frontend on every request, which is def. sub-optimal.

Refactor that functionality out. Really, it needs to be in mu-plugins directly, not part of VIP Dashboard either.

### LINKED ISSUE #45: Various removed shared plugins are referenced
`WPCOM_VIP_Plugins_UI::setup_globals` references various shared plugins which we've removed, these should no longer be referenced.

Hopefully a simple removal job. :smile:

### LINKED ISSUE #48: Activating a plugin with a fatal error is not possible and returns no error
When someone attempts to activate a plugin containing a fatal error in vanilla WordPress, the plugin is not activated and the UI displays an error message explaining why the plugin wasn't activated.

When someone attempts to activate a plugin containing a fatal error in VIP Go, the plugin is not activated but no error message is shown.

An error message should be displayed as it is in vanilla WordPress.

### LINKED ISSUE #49: Plugins activated via wpcom_vip_load_plugin do not appear activated in the UI
To reproduce:
1. Add a plugin, e.g. Field Manager, to the `plugins` directory on your repository
2. Activate the plugin via code, e.g. `wpcom_vip_load_plugin( 'fieldmanager/fieldmanager.php' );`
3. Visit the WP Admin > Plugins screen

Expected: Field Manager should show as activated with a message "Enabled via your theme's code"

Actual: Field Manager shows as inactive, BUT is actually active

### LINKED ISSUE #52: Switch back to core plugins screen
With the release of shiny updates (https://wordpress.org/plugins/shiny-updates/) in core, we should switch back to the standard plugins screen and find a different way to feature our partner plugins. Perhaps just a nice admin page or area at the top of the current plugins search screen.

### PR DESCRIPTION
**Pull request by scottsweb**
Requires: https://github.com/Automattic/vip-go-mu-plugins/pull/754

Closes #52 
Closes #49 
Should close #48 
Closes #45 
Closes #43 
Closes #38 

screenshot-05-10-2017-11 15 18

screenshot-06-10-2017-16 48 13

screenshot-09-10-2017-12 11 31

### CODE REVIEW

File: vip-dashboard.php [hunk 1]
```diff
@@ -346,3 +326,205 @@ function wpcom_vip_menu_order( $menu_ord ) {
 
 	return $vip_order;
 }
+
+function wpcom_vip_featured_plugins() {
```
Comment (mjangda) [inline vip-dashboard.php]: Should rename this to `wpcom_render_vip_featured_plugins`.

File: vip-dashboard.php [hunk 2]
```diff
@@ -346,3 +326,205 @@ function wpcom_vip_menu_order( $menu_ord ) {
...
+	if ( ! ( 'plugins' === $screen->id || 'plugins-network' === $screen->id ) ) {
+		return;
+	}
+
+	$plugins = wp_cache_get( 'wpcom_vip_featured_plugins' );
+
+	if ( false === $plugins ) {
+		$plugins = array();
+		$url_for_featured_plugins = 'https://vip.wordpress.com/wp-json/vip/v1/partners?type=technology';
+		$api = vip_safe_wp_remote_get( $url_for_featured_plugins, false, 3, 5 );
```
Comment (mjangda) [inline vip-dashboard.php]: Minor: rename `$api` to `$response` for clarity.

File: vip-dashboard.php [hunk 3]
```diff
@@ -346,3 +326,205 @@ function wpcom_vip_menu_order( $menu_ord ) {
...
+
+		if ( ! $api || is_wp_error( $api ) ) {
+			// fail silently
```
Comment (mjangda) [inline vip-dashboard.php]: Should we `error_log` or `trigger_error` (as a warning)?

File: vip-dashboard.php [hunk 4]
```diff
@@ -346,3 +326,205 @@ function wpcom_vip_menu_order( $menu_ord ) {
...
+			return;
+		}
+
+		$plugins = json_decode( $api['body'] );
+		if ( ! empty( $plugins ) ) {
```
Comment (mjangda) [inline vip-dashboard.php]: We can reverse the condition to simplify things:

```
if ( empty( $plugins ) ) {
    return;
}

wp_cache_set( ... );
```

File: vip-dashboard.php (hunk 1 above)
Comment (mjangda) [reply vip-dashboard.php]: Also, generally, it's a good idea to separate the data fetching and rendering portions, so we could have the API call in one function and the HTML output in another.

File: vip-dashboard.php [hunk 5]
```diff
@@ -346,3 +326,205 @@ function wpcom_vip_menu_order( $menu_ord ) {
...
+				</a>
+			</div>
+			<?php
+		}
+		?>
+	</div>
+	<?php
+}
+add_action( 'admin_notices', 'wpcom_vip_featured_plugins', 99 );
+add_action( 'network_admin_notices', 'wpcom_vip_featured_plugins', 99 );
```
Comment (mjangda) [inline vip-dashboard.php]: Should we add an inline comment noting why we're using `admin_notices` (since it's a non-standard hook for this type of data)?

File: vip-dashboard.php [hunk 6]
```diff
@@ -346,3 +326,205 @@ function wpcom_vip_menu_order( $menu_ord ) {
...
+ * @return null
+ */
+function wpcom_vip_plugins_ui_admin_enqueue_scripts() {
+	$screen = get_current_screen();
+	if ( 'plugins' === $screen->id || 'plugins-network' === $screen->id ) {
+		wp_register_style( 'vip-plugins-style', plugins_url( '/assets/css/plugins-ui.css', __FILE__ ) , '3.0' );
+		wp_enqueue_style( 'vip-plugins-style' );
+
+		wp_register_script( 'vip-plugins-script', plugins_url( '/assets/js/plugins-ui.js', __FILE__ ), array( 'jquery' ), '3.0', true );
+		wp_enqueue_script( 'vip-plugins-script' );
```
Comment (mjangda) [inline vip-dashboard.php]: Minor: no need to call register and then enqueue. If we don't need to allow re-use of the script/style, we can just call enqueue (which handles register for us).
