### PR TITLE
A few little fixes

### LINKED ISSUE #67: Minify built JavaScript
We should minify the built JavaScript file

### PR DESCRIPTION
**Pull request by scottsweb**
* Minify JS on each build - Closes #67
* PHPCS fixes and recommendations - not perfect, but much better 📈 . I didn't spend a huge amount of time of files we know will be removed at a later date

### CODE REVIEW

File: vip-dashboard.php [hunk 1]
```diff
@@ -87,75 +87,65 @@ function vip_dashboard_page() {
 		data-asseturl="<?php echo esc_attr( plugins_url( '/assets/', __FILE__ ) ); ?>"
 		data-email="<?php echo esc_attr( $email ); ?>"
 		data-name="<?php echo esc_attr( $name ); ?>"
-		data-adminurl="<?php echo admin_url( 'admin.php' ); ?>"
+		data-adminurl="<?php echo esc_attr( admin_url( 'admin.php' ) ); ?>"
```
Comment (nickdaugherty) [inline vip-dashboard.php]: This should actually be `esc_url()`.

Comment (scottsweb) [inline vip-dashboard.php]: Sorted :)
