### PR TITLE
Fix sender

### LINKED ISSUE #62: Filter the 'from' address when sending support requests from dashboard
WP 4.6 made some changes to the underlying email handling, which necessitated this change:

https://github.com/Automattic/vip-go-mu-plugins/pull/277

The need for that will go away in 4.6.1 (we can set `Sender` again), but in the meantime, we're sending emails from the wrong address when creating tickets from the dashboard.

Instead, we should be using `vip-support@wordpress.com `, which we set via a header...but with the `wp_mail_from` filter, the header is overridden, which breaks it. 

So temporarily, we should filter `wp_mail_from` here, and remove the filter after sending is complete.

### PR DESCRIPTION
**Pull request by scottsweb**
Hope this is what was needed @nickdaugherty 

Closes #62

### CODE REVIEW

File: vip-dashboard.php [hunk 1]
```diff
@@ -99,6 +99,8 @@ function vip_dashboard_page() {
  */
 function vip_contact_form_handler() {
 
+	add_filter( 'wp_mail_from', 'wpcom_vip_filter_from_dashboard' );
```
Comment (nickdaugherty) [inline vip-dashboard.php]: Would it be possible to move this down closer where it's used? No sense in setting it earlier than necessary, because other code could trigger a wp_mail() in the meantime.

**Comment by scottsweb** [comment]
I have gone ahead an fixed moved this @nickdaugherty and merged/closed so I can get on with a few other last bits.
